spring:
  h2:
    console:
      enabled: true
      path: /h2_musinsa

  datasource:
    url: jdbc:h2:mem:test
    username: musinsa
    password: musinsa
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

logging.level:
  root: info
  org.hibernate: debug